# Dockerfile Template
# Ubuntu based container
#
# VERSION	1.0

# use the official ubuntu base image
FROM ubuntu:latest

# make sure the package repository is updated
RUN apt-get update

########################################
# Put your configuration commands here


